#!/usr/bin/env python3

import sys
import csv
import jinja2
import datetime

_, csv_filename, record_number, template_filename, output_filename = sys.argv
record_number = int(record_number) - 1

from jinja2 import Environment, FileSystemLoader, select_autoescape
jinjaenv = Environment(loader=FileSystemLoader('.'))
template = jinjaenv.get_template(template_filename)

base_context = dict(date=datetime.datetime.now().strftime("%d %B %Y"))

with open(csv_filename) as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for n, row in enumerate(csv_reader):
        context = dict(row.items())
        context.update(base_context)
        context["username"] = "ga" + context["county"].lower().split()[0]
        if n == record_number:
            with open(output_filename, "w") as outfile:
                outfile.write(template.render(**context))
                sys.exit(0)


sys.exit(3)
